import express from "express";
import userRouter from "./routes/User.route.js";
import bookRouter from "./routes/Book.route.js";
import checkoutRouter from "./routes/Checkout.route.js";
const app = express();
app.use(express.json({ limit: "16kb" }));
app.use(express.urlencoded({ extended: true, limit: "16kb" }));
app.use(userRouter);
app.use(bookRouter);
app.use(checkoutRouter);
export default app;
